export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';
export const RECEIVE_ARTICLE_LIST_MORE = 'RECEIVE_ARTICLE_LIST_MORE';

export const RECEIVE_BEAUTY_LIST = 'RECEIVE_BEAUTY_LIST';
//http://gank.io/api/data/iOS/20/2
